Part 1: Theoretical Question

Q1. What are the different data structures used in Tensorflow?. Give some examples

Ans:-Three types of data structures in Tensorflow.
       i.Tensor
         ii.Variables
           iii.Sparse Tensor

In [3]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 2.9 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 83.0 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 17.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.9/22.9 MB 58.5 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 84.2 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 51.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 81.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 63.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━

In [4]:
import tensorflow as tf
Tensor=tf.constant([1,2,3,4,5,6])

2023-06-21 02:36:15.312810: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-21 02:36:15.382455: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-21 02:36:15.383463: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-21 02:36:16.462497: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [5]:
Tensor

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [6]:
import tensorflow as tf
variable=tf.Variable([1,2,3,4,5,6])

In [7]:
variable

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [8]:
import tensorflow as tf
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 1], [2, 3]], values=[2, 4], dense_shape=[3, 4])

In [9]:
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 1]
 [2 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([2 4], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))

Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examples

In [ ]:
Ans:-TensorFlow Constant:
        A constant is a data structure that holds a fixed value and cannot be modified after creation.
        
    TensorFlow Variable:
        A variable is a mutable data structure that holds a value that can be modified during training.

In [14]:
import tensorflow as tf
constant=tf.constant([1,2,3,4])
constant=constant+2
constant

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 5, 6], dtype=int32)>

In [21]:
import tensorflow as tf
variable=tf.Variable([1,2,3,4])
variable=variable+3
variable

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 7], dtype=int32)>

Q3.Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

In [ ]:
Ans:-Matrix Addition:
        Matrix addition involves adding corresponding elements of two matrices of the same shape.
        
        Matrix Multiplication:
            Matrix multiplication involves multiplying corresponding elements of two matrices and summing the results.  

In [24]:
import tensorflow as tf
matrix1 = tf.constant([[5, 2], [6, 4]])
matrix2 = tf.constant([[2, 6], [3, 5]])
result=tf.add(matrix1,matrix2)
result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [9, 9]], dtype=int32)>

In [27]:
import tensorflow as tf
matrix1=tf.constant([[5,4],[4,2]])
matrix2=tf.constant([[2,3],[4,6]])
result=tf.matmul(matrix1,matrix2)
result

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 39],
       [16, 24]], dtype=int32)>

Part 2: Practical Implementation
Talk 1: Creating and Manipulating Matricek

Q1.Create a normal matrix A with dimensions 3*3, using TensorFlows random_normal function. Display the
values of matrix A.

In [45]:
import tensorflow as tf
tf.random.normal(shape=(3,3),mean=10,stddev=5)
ran=tf.random.normal(shape=(3,3),mean=10,stddev=5)
print(ran)
print(matrix1)

tf.Tensor(
[[10.124386  11.937936   8.499355 ]
 [ 3.9279404 11.490804   9.536015 ]
 [ 9.314747  12.86846    8.300713 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[5 4]
 [4 2]], shape=(2, 2), dtype=int32)


Q2Create a Gaussian matrix B with dimensions x, using TensorFlows truncated_normal function. Display
the values of matrix B

In [90]:
import tensorflow as tf
x = 4
B = tf.random.truncated_normal(shape=(x, x))
print(B)

tf.Tensor(
[[-0.61902046  0.3112488   0.90987027 -0.07019015]
 [ 0.12523243  0.88540345  0.37935388  0.5791472 ]
 [-0.26269272  0.01906765  0.760083   -0.5485437 ]
 [-1.4248438   0.5241498   1.7427286   0.34226114]], shape=(4, 4), dtype=float32)


Q3.Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a
mean of 2 and a standard deviation of 0.x, using TensorFlows random.normal function. Display the values
of matrix Cc

In [70]:
import tensorflow as tf
tf.random.normal(shape=(2,2),mean=3,stddev=0.5)
ran=tf.random.normal(shape=(2,2),mean=3,stddev=0.5)
print(ran)
print(matrix1)

tf.Tensor(
[[2.8233745 2.2504487]
 [3.206153  1.8291464]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[5 4]
 [4 2]], shape=(2, 2), dtype=int32)


Q4.Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [75]:
import tensorflow as tf
matrix1 = tf.constant([[5, 2], [6, 4]])
matrix2 = tf.constant([[2, 6], [3, 5]])
D=tf.add(matrix1,matrix2)
D

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 8],
       [9, 9]], dtype=int32)>

Q5.Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [74]:
import tensorflow as tf
matrix1=tf.constant([[5,4],[4,2]])
matrix2=tf.constant([[2,3],[4,6]])
E=tf.matmul(matrix1,matrix2)
E

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 39],
       [16, 24]], dtype=int32)>

Talk 2: Per;orming Additional Matrix Operationk

Q1.Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform
functionc

In [83]:
F=tf.random.uniform(shape=(2,2),minval=10,maxval=25)
F

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19.17876  , 17.352917 ],
       [14.7010145, 14.061657 ]], dtype=float32)>

Q2.Calculate the transpose of matrix F and store the result in matrix Gc

In [86]:
import tensorflow as tf
F = tf.constant([[19.17876  , 17.352917 ],
       [14.7010145, 14.061657 ]])
G = tf.transpose(F)
print(G)

tf.Tensor(
[[19.17876   14.7010145]
 [17.352917  14.061657 ]], shape=(2, 2), dtype=float32)


Q3.Calculate the elementDwise exponential of matrix F and store the result in matrix Hc

In [89]:
import tensorflow as tf
F = tf.constant([[19.17876  , 17.352917 ],
       [14.7010145, 14.061657 ]])
H = tf.exp(F)
print(H)

tf.Tensor(
[[2.1341742e+08 3.4377632e+07]
 [2.4242058e+06 1.2790868e+06]], shape=(2, 2), dtype=float32)


Q4.Create a matrix I by concatenating matrix F and matrix G horizontally

In [98]:
import tensorflow as tf

F = tf.constant([[19.17876  , 17.352917 ],
                [14.7010145, 14.061657 ]])
G = tf.constant([[19.17876  ,14.7010145],
                [17.352917 ,14.061657 ]])
I = tf.concat([F, G], axis=1)
print(I)

tf.Tensor(
[[19.17876   17.352917  19.17876   14.7010145]
 [14.7010145 14.061657  17.352917  14.061657 ]], shape=(2, 4), dtype=float32)


Q5.Create a matrix J by concatenating matrix F and matrix H vertically.

In [105]:
import tensorflow as tf

F = tf.constant([[19.17876  , 17.352917 ],
                [14.7010145, 14.061657 ]])
H = tf.constant([[2.1341742e+08 ,3.4377632e+07],
                [2.4242058e+06, 1.2790868e+06]])
I = tf.concat([F, H], axis=0)
print(I)

tf.Tensor(
[[1.91787605e+01 1.73529167e+01]
 [1.47010145e+01 1.40616570e+01]
 [2.13417424e+08 3.43776320e+07]
 [2.42420575e+06 1.27908675e+06]], shape=(4, 2), dtype=float32)
